---
title: "mRNA"
author: "Gabriel"
date: "`r Sys.Date()`"
output: html_document
---

#Pacotes
```{r setup, include=FALSE}
library(AnnotationDbi)
library(dendextend)
library(EnhancedVolcano)
library(FactoMineR); library(factoextra)
library(clariomshumantranscriptcluster.db)
library(pd.clariom.d.human)
library(GEOquery)
library(limma)
library(oligo)
library(pheatmap)
library(sva)
library(tidyverse)
library(affycoretools)

### Pacotes
library(reshape2)
library(clusterProfiler)
library(dendextend)
library(DESeq2)
library(enrichplot)
library(fgsea)
library(GOplot)
library(org.Hs.eg.db)
library(pheatmap)
library(UpSetR)
library(rstatix)
library(tidyverse)
library(usethis)
```

```{r}
my_id <- "GSE183140"

geo <- getGEO(my_id)
gse <- geo[1][[1]]

pdata <- pData(gse)
pdata <- pdata %>% filter(`cell line:ch1` == "Caki-1")
  #drug resistance:ch1 é o grupo
sample_info <- pdata %>% dplyr::select(title, `drug resistance:ch1`)

gse <- gse[,rownames(pdata)]

pdata['cel_file'] <- str_split(pdata$supplementary_file,"/") %>% map_chr(tail,1) #Criar nova coluna (cel_file) contendo o nome do arquivo de cada leitura. Importante para manter a ordem das leituras ao importar os dados de leitura

#Importar com a ordem correta, garantindo que as leituras estao mapeadas para as amostras certas
gse_celdata <-  read.celfiles(paste0('GSE183140_mRNA/',pdata$cel_file),phenoData=phenoData(gse))
```

```{r}
gse_celdata@annotation
eset <- rma(gse_celdata)

fData(eset)
eset <- annotateEset(eset, pd.clariom.d.human, columns = c('PROBEID', "ENTREZID", "SYMBOL", "GENENAME"))

pd.clariom.d.human@tableInfo

oligo::hist(eset)
fData(eset) %>% View()
```

#Filtros 1
##Anotação dupla e SYMBOL NA
```{r}
anno_gse <- fData(eset)
anno_gse <- subset(anno_gse, !is.na(SYMBOL))

anno_grouped <- group_by(anno_gse, PROBEID)
anno_summarized <- dplyr::summarize(anno_grouped, n_of_matches = n_distinct(SYMBOL))
#Nenhum probe com leitura duplicada, provavelmente devido o metodo de anotacao do affycoretools
hist(anno_summarized)

eset <- subset(eset, !is.na(fData(eset)$SYMBOL))
fData(eset) %>% View()

eset <- subset(eset, !grepl("AceView", fData(eset)$GENENAME))
eset <- subset(eset, !grepl("pseudogene", fData(eset)$GENENAME))
eset <- subset(eset, !grepl("---", fData(eset)$GENENAME))
eset

n_occur <- data.frame(table(fData(eset)$SYMBOL))
n_occur[n_occur$Freq>1,]

```

##Baixas leituras
```{r}
exp_eset <- exprs(eset)
```

```{r}
gse_medians <- rowMedians(exp_eset)

hist(gse_medians, 100, freq=F, col='cornsilk')
abline(v=2.8)

threshold <- apply(eset, 1, function(x) {
  sum(x > 2.8) >=6
})

table(threshold)

eset_filtered <- subset(eset, threshold)
exp_filtered <- exprs(eset_filtered)

oligo::hist(eset_filtered)
```

##Dendograma e PCA
```{r}
dist <- dist(t(exp_filtered))
hc <- hclust(dist)
dend <- as.dendrogram(hc)

dend %>% 
  color_labels(labels=colnames(exp_filtered[,1:3]), col='blue') %>% 
  color_labels(labels=colnames(exp_filtered[,4:6]), col='orange2') %>% 
  color_labels(labels=colnames(exp_filtered[,7:9]), col='darkred')%>% 
  plot()

legend('topright',
       legend=c('Caki parental', 'Caki Clone 1', 'Caki Clone 2'),
       col=c('blue', 'orange2', 'darkred'),
       pch=c(20,20,20))
```

```{r}
pca <- PCA(t(exp_filtered), graph = T)



pdf("Figuras/PCA - clones.pdf", width = 6, height = 4)
fviz_pca_ind(pca,
             mean.point=F, 
             geom.ind='point', pointshape=21,
             fill.ind=pdata$description,
             addEllipses = T, ellipse.type='confidence')+
    scale_fill_manual(values=c("orange2", 'darkred', "blue"), labels=c('Clone 1 - Caki resistant', 'Clone 2 - Caki resistant', 'Caki Parental'))+
  scale_color_manual(values=c("orange2", 'darkred', "blue"), labels=c('Clone 1 - Caki resistant', 'Clone 2 - Caki resistant', 'Caki Parental'))+
  theme_classic()#+]

fviz_contrib(X = pca, choice = 'var')
  
dev.off()
  
  
fviz_pca_ind(pca,
             mean.point=F,
             geom.ind='point', pointshape=21,
             fill.ind=pdata$`drug resistance:ch1`,
             addEllipses = T, ellipse.type='confidence')+
  theme_classic()
```

#DEG
```{r}
pdata$Grupo <- str_replace_all(pdata$description, "Gene expression data from *", "")

design <- model.matrix(~0+pdata$Grupo)
colnames(design) <- c("CakiParental", 'CakiResC1', 'CakiResC2')

contrastMatrix <- makeContrasts(CakiResC1 - CakiParental , CakiResC2 - CakiParental, levels=colnames(design))
contrastMatrix

fit <- lmFit(eset_filtered, design)
fit <- contrasts.fit(fit, contrasts = contrastMatrix)
fit2 <- eBayes(fit)

res_c1 <- topTable(fit2, number = Inf, coef = 1)
res_c2 <- topTable(fit2, number = Inf, coef = 2)

summary(decideTests(fit2, lfc = 1.5, adjust.method = 'fdr', p.value = 0.05, coef=1))

res_c1.res <- filter(res_c1, abs(logFC) >=1.5, adj.P.Val <=0.05) %>% dplyr::arrange(dplyr::desc(abs(logFC))) %>% distinct(SYMBOL, .keep_all = T)
res_c2.res <- filter(res_c2, abs(logFC) >=1.5, adj.P.Val <=0.05) %>% dplyr::arrange(dplyr::desc(abs(logFC))) %>% distinct(SYMBOL, .keep_all = T)

venn <- BioVenn::draw.venn(list_x = res_c1.res$SYMBOL,
                   list_y=res_c2.res$SYMBOL, list_z = NULL, x_c = "orange", y_c = 'red',
                   title = NULL, subtitle = NULL,
                   xtitle = "Caki clone 1", ytitle = "Caki clone 2", nr_s = 1.5,
                   output = "pdf", width = 500, height = 500)
venn$xy
venn
res_c1.xy <- filter(res_c1.res, SYMBOL %in% venn$xy)
res_c2.xy <- filter(res_c2.res, SYMBOL %in% venn$xy)



BioVenn::draw.venn(list_x = filter(res_c1.xy, logFC < 0)$SYMBOL,
                   list_y =filter(res_c2.xy, logFC < 0)$SYMBOL,
                   list_z = NULL)

```

#Heatmap
```{r}
exp_xy <- exp_filtered %>% as.data.frame() %>% filter(rownames(.) %in% res_c1.xy$PROBEID)

pdata$Grupo2 <- c("Parental_1", "Parental_2", "Parental_3", "Caki.1_1", "Caki.1_2", "Caki.1_3", "Caki.2_1", "Caki.2_2", "Caki.2_3")
colnames(exp_xy) <- pdata$Grupo2

exp_xy <- exp_xy %>% rownames_to_column(var="PROBEID") %>% 
  left_join(., res_c1.xy[,c(1,3)])

exp_xy <- dplyr::select(exp_xy, "PROBEID", "Caki.1_1", "Caki.1_2", "Caki.1_3", "Parental_1", "Parental_2", "Parental_3", "Caki.2_1", "Caki.2_2", "Caki.2_3", "SYMBOL")

ann <- as.data.frame(colnames(exp_xy[2:10]))
ann$Cell <- ann$`colnames(exp_xy[2:10])` %>% gsub("_.*", "", .)
ann <- column_to_rownames(ann, var = "colnames(exp_xy[2:10])")

ann$Cell 


pheatmap(exp_xy,
         cluster_cols = F,
         scale="row",
         annotation_col = ann,
         annotation_colors = list(Cell = c(Caki.1 = "yellow",
                                           Parental = "green",
                                           Caki2 = "blue")))

pheatmap(exp_xy[,2:10],
         border_color = NA,
         cluster_cols = F, #gaps_col = 4,
         cluster_rows = T,
         #treeheight_row = 0,
         color=colorRampPalette(c('#175290','#55a1fa', 'white','#fe0131', 'darkred'))(100),
         show_colnames = F,
         show_rownames = T,
         labels_row  = exp_xy$SYMBOL,
         scale="row", 
         fontsize_row = 7,
         annotation_col = ann,
         annotation_colors = list(Cell = c(Caki.1 = "orange",
                                           Parental = "blue",
                                           Caki.2 = "darkred")))
```

#Volcanos
```{r}


EnhancedVolcano(res_c1, x = "logFC", y = "P.Value", lab = res_c1$SYMBOL, 
                title = "Caki clone 1 vs Parental", subtitle = NULL, caption = NULL,
                pCutoffCol = "adj.P.Val", pCutoff = 0.05, FCcutoff = 1.5
                )+
  theme_classic()+
  theme(legend.position = 'top',
        legend.title = element_blank())
ggsave("Figuras/Volcano_Caki1.svg", width = 6, height = 6, bg='white')


EnhancedVolcano(res_c2, x = "logFC", y = "P.Value", lab = res_c1$SYMBOL, 
                title = "Caki clone 2 vs Parental", subtitle = NULL, caption = NULL,
                pCutoffCol = "adj.P.Val", pCutoff = 0.05, FCcutoff = 1.5
                )+
  theme_classic()+
  theme(legend.position = 'top',
        legend.title = element_blank())
ggsave("Figuras/Volcano_Caki2.pdf", width=6, height= 6, bg='white')
```

#Barplot
```{r}
res.xy <- rbind(
  res_c1.xy %>% mutate(Clone = "Caki 1") %>% dplyr::select(SYMBOL, logFC, P.Value, adj.P.Val, Clone),
  res_c2.xy %>% mutate(Clone = "Caki 2") %>% dplyr::select(SYMBOL, logFC, P.Value, adj.P.Val, Clone)
) %>% 
  mutate(fc=ifelse(logFC>0, "Up", "Down"))

pdf("Figuras/Barplot.pdf", width = 14, height = 6)
res.xy %>% ggplot(aes(reorder(SYMBOL, -logFC), logFC, fill=Clone))+
  geom_col(position = "identity", alpha = .65, color='black')+
  scale_fill_manual(values=c("orange2", "darkred"))+
  theme_classic()+
  ggpubr::rotate_x_text(angle=45)+
  labs(x=NULL)+
  theme(legend.position = c(.9, .8),
        axis.text.y = element_text(size=8, color = 'black'),
        axis.text.x = element_text(size=10, color = 'black'))+
  coord_flip()

dev.off()


res.xy %>% filter(logFC>0) %>% 
  mutate(plot = ifelse(Clone == "Caki 1", logFC, logFC*-1)) %>% 
  ggplot(aes(plot, reorder(SYMBOL, logFC), fill=Clone))+
  geom_col()+
  geom_vline(xintercept = 0)+
  theme_classic()+
  labs(x="Absolute Fold Change", y=NULL)+
  scale_fill_manual(values=c("orange2", "darkred"))+
  theme(axis.text.y = element_text(size=8, color = 'black'),
        axis.text.x = element_text(size=10, color = 'black'))
  


res.xy %>% filter(logFC<0) %>% 
  mutate(plot = ifelse(Clone == "Caki 1", logFC, logFC*-1)) %>% 
  ggplot(aes(plot, reorder(SYMBOL, logFC), fill=Clone))+
  geom_col()+
  geom_vline(xintercept = 0)+
  theme_classic()+
  labs(x="Absolute Fold Change", y=NULL)+
  scale_fill_manual(values=c("orange2", "darkred"))+
  theme(axis.text.y = element_text(size=8, color = 'black'),
        axis.text.x = element_text(size=10, color = 'black'))

pdf("Figuras/Count degs.pdf", width = 3, height = 3)
res.xy %>% filter(Clone=='Caki 1') %>% #filter apenas para nao repetir cada resultado para cada clone. clones estao iguais
  ggplot(aes(fc, fill=fc))+
  geom_bar(stat='count', position='dodge', width = .75)+
  stat_count(geom = "text", colour = "white", size = 4, aes(label = ..count..), vjust=1.5)+
  scale_fill_manual(values=c('#55a1fa', '#fe0131'), guide='none')+
  theme_classic()+
  labs(x=NULL, y="DEGs")+
  coord_cartesian(xlim=c(0.5,2.5), expand = F, ylim=c(0,70))+
  theme(axis.text = element_text(color='black'))
dev.off()

```

##maiores variacoes
```{r}
res.var <- data.frame(SYMBOL = venn$xy)

res.var <- left_join(res.var, res_c1.xy[,c(3,5,9)])
res.var <- res.var %>% dplyr::rename(C1_logFC = 2, C1_adj.pval = 3)

res.var <- left_join(res.var, res_c2.xy[,c(3,5,9)])
res.var <- res.var %>% dplyr::rename(C2_logFC = 4, C2_adj.pval = 5)
res.var$fc <- ifelse(res.var$C1_logFC > 0, "Up", "Down")

res.var$Var <- res.var$C1_logFC / res.var$C2_logFC

top.var <- slice_max(res.var, order_by = abs(Var), n=20)
openxlsx::write.xlsx(res.var, file='DEGs Caki.xlsx', asTable = T)

pdf("Figuras/Clones variance.pdf", width = 6, height = 8)
top.var %>% ggplot(aes(reorder(SYMBOL, abs(Var)), abs(Var), fill=fc))+
  geom_col()+
  labs(x=NULL, y="Absolute variance (fold) between Caki clones", title="Top 20 genes with most variance between Caki clones")+
  theme_classic()+
  coord_flip()+
  scale_fill_manual(values=c('#55a1fa', '#fe0131'), name='Fold Change')+
  theme(axis.text = element_text(size=10, colour = 'black'),
        legend.position = c(.8,.2))
dev.off()

```

#Enriquecimento
```{r}
xy_GO <- enrichGO(venn$xy, OrgDb = org.Hs.eg.db, keyType = "SYMBOL", ont = 'all')
xy_GO <- xy_GO@result

xy_down <- enrichGO(gene = filter(res.var, fc == 'Down')$SYMBOL,
                    OrgDb = org.Hs.eg.db, keyType = "SYMBOL", ont = 'all')
xy_down <- xy_down@result

xy_up <- enrichGO(gene = filter(res.var, fc == 'Up')$SYMBOL,
                    OrgDb = org.Hs.eg.db, keyType = "SYMBOL", ont = 'all')
xy_up <- xy_up@result
```

Enriquecimento dos clones de forma separada para encontrar resultados de autofagia
```{r}
##Dfs com os valores de cada clone, independentes
#res_c1.res
#res_c2.res
```

##GSEA
```{r}

##Preparo

ranks.c1 <- res_c1.res[order(res_c1.res$logFC, decreasing = T),]$logFC
names(ranks.c1) <- res_c1.res[order(res_c1.res$logFC, decreasing = T),]$SYMBOL

ranks.c2 <- res_c2.res[order(res_c2.res$logFC, decreasing = T),]$logFC
names(ranks.c2) <- res_c2.res[order(res_c2.res$logFC, decreasing = T),]$SYMBOL

msigdbr::msigdbr_collections() %>% print(n=Inf)
H <- msigdbr::msigdbr(species = "Homo sapiens", category = "H")
H.symbol <- dplyr::select(H, gs_name, gene_symbol)

CPs <- rbind(
   msigdbr::msigdbr(species = "Homo sapiens", category = "C2", subcategory = "CP:KEGG"),
   msigdbr::msigdbr(species = "Homo sapiens", category = "C2", subcategory = "CP:REACTOME"),
   msigdbr::msigdbr(species = "Homo sapiens", category = "C2", subcategory = "CP:WIKIPATHWAYS"))
CPs.symbol <- dplyr::select(CPs, gs_name, gene_symbol)


##Enriquecimento
gsea.hallmarks_c1 <- GSEA(ranks.c1, TERM2GENE = H.symbol)
gsea.hallmarks.c1 <- gsea.hallmarks_c1@result

gsea.cps_c1 <- GSEA(ranks.c1, TERM2GENE = CPs.symbol)
gsea.cps.c1 <- gsea.cps_c1@result

gsea.hallmarks_c2 <- GSEA(ranks.c2, TERM2GENE = H.symbol)
gsea.hallmarks.c2 <- gsea.hallmarks_c2@result

gsea.cps_c2 <- GSEA(ranks.c2, TERM2GENE = CPs.symbol)
gsea.cps.c2 <- gsea.cps_c2@result
```


#GO
```{r}
go.c1_up <- enrichGO(filter(res_c1.res, logFC > 0)$SYMBOL, OrgDb = org.Hs.eg.db, keyType = "SYMBOL", ont = "bp")
go.c1_up <- go.c1_up@result

go.c1_down <- enrichGO(filter(res_c1.res, logFC < 0)$SYMBOL, OrgDb = org.Hs.eg.db, keyType = "SYMBOL", ont="bp")
go.c1_down <- go.c1_down@result

go.c2_up <- enrichGO(filter(res_c2.res, logFC > 0)$SYMBOL, OrgDb = org.Hs.eg.db, keyType = "SYMBOL", ont = "bp")
go.c2_up <- go.c2_up@result

go.c2_down <- enrichGO(filter(res_c2.res, logFC < 0)$SYMBOL, OrgDb = org.Hs.eg.db, keyType = "SYMBOL", ont="bp")
go.c2_down <- go.c2_down@result
```

```{r}
mapIds(org.Hs.eg.db, keys = res_c1.res$SYMBOL,
       column = "ENTREZID", keytype = "SYMBOL")

enrichKEGG(mapIds(org.Hs.eg.db, 
                  keys = filter(res_c2.res, logFC > 0)$SYMBOL,
                  column = "ENTREZID", keytype = "SYMBOL"), 
           organism = "hsa", keyType = "kegg")
```

#Autophagy
```{r}
autophagy <- readxl::read_excel("AutophagyDb.xlsx")
autophagy <- autophagy[grepl("\\d", autophagy$`  A  (top)`),]
colnames(autophagy) <- c("geneID", "Name", "Symbol")

BioVenn::draw.venn(list_x = res_c2$SYMBOL,
                   list_y=autophagy$Symbol, list_z = NULL, x_c = "orange", y_c = 'red',
                   title = NULL, subtitle = NULL,
                   xtitle = "Caki clone 1", ytitle = "Autophagy", nr_s = 1.5)
                   #output = "pdf", width = 500, height = 500)

      
res.autophagy <- rbind(
  res_c1.res %>% mutate(Clone = "Caki 1") %>% dplyr::select(SYMBOL, logFC, P.Value, adj.P.Val, Clone) %>%
    filter( SYMBOL %in% c("NRG1",     "NPC1","EGFR", "CDKN1B",  "PINK1" ,   "MYC" ,     "DAPK1",    "EIF4EBP1", "ATG4A" )),
  res_c2.res %>% mutate(Clone = "Caki 2") %>% dplyr::select(SYMBOL, logFC, P.Value, adj.P.Val, Clone) %>% 
    filter(SYMBOL %in% c("ERN1" ,    "NRG1",     "MAP1LC3C", "PPP1R15A", "ATG4A",    "SERPINA1", "CASP4",    "DDIT3" ))
) %>% 
  mutate(fc=ifelse(logFC>0, "Up", "Down"))


res.autophagy %>% ggplot(aes(as.factor(Clone), reorder(SYMBOL, logFC), fill=logFC))+
  geom_tile()+
  scale_fill_gradient2(low = "red", mid = 'white', high = 'deepskyblue4')+
  #scale_fill_gradientn(colours = c("red",  "white","deepskyblue"))+
  coord_fixed()+
  labs(y=NULL, x=NULL)+
  #geom_text(aes(label=round(adj.P.Val,4)))+
  theme_classic()+
  ggpubr::rotate_x_text(angle=90)+
  theme(axis.text = element_text(size=12, color='black'))
```

```{r}
mirtar %>% filter(miRNA %in% c("hsa-miR-23b-3p", "hsa-miR-133a-3p", "hsa-miR-133a-5p")) %>% openxlsx::write.xlsx(., "Alvos_133a_23b.xlsx")

```

